#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

PANEL_FIFO=/tmp/lemonfifo
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &

. ~/.config/bspwm/panel/source

cat "$PANEL_FIFO" | ~/.config/bspwm/panel/panel_bar | lemonbar \
-g x"$PANEL_HEIGHT" \
-f "$PANELFONT" \
-f "$PANELFONT_BOLD" \
-f "$ICONFONT" \
-F "$COLOR_FG" \
-B "#000000" \
-u 2 | sh &

wait
