#! /bin/sh
#
# Example panel for LemonBoy's bar

. ~/.config/bspwm/panel/source

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		R*)
			right="${line#?}"
			;;
		M*)
			music="${line#?}"
			;;
    U*)
      mail="${line#?}"
      ;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$YELLOW}\uE1C2%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$LIGHTRED}\uE1C2%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$RED}\E1C4%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$BLUE}\uE1C3%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$WHITE}\uE1BC%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$RED}\E1C4%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	echo -e "%{l}${music} %{c}${wm_infos} %{r}${right}"
done
